services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: video_retrieval_postgres
    environment:
      POSTGRES_DB: videodb_creative_v2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d videodb_creative_v2"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: